### ISSUE TITLE
什么时候能上传一下安装包，好想体验

### ISSUE THREAD

**Issue by ghost** [UopyTechSpeak/CompuMon#1]
感觉这个项目真好，可以识别出电脑的型号，值得研究一下！
希望早日能够上线安装包

**Comment by UopyTechSpeak** [comment]
Hello! I am the developer of this project, and I have seen the question you submitted. For now, I am conducting testing and will upload the installation package if there are no issues.

I will develop version 1.0.0 for multilingual adaptation and compatibility with multiple systems in the future. Stay tuned!

Thank you for submitting this question!
